name: remote ssh command
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd api.thubongstore.online/tako_shoping
          git pull origin main
          source /home/gaubongs/nodevenv/api.thubongstore.online/tako_shopping/backend/20/bin/activate
          cd /home/gaubongs/api.thubongstore.online/tako_shopping/backend
          npm install
          source /home/gaubongs/nodevenv/api.thubongstore.online/tako_shopping/frontend/10/bin/activate
          cd /home/gaubongs/api.thubongstore.online/tako_shopping/frontend
          npm run build
          cp -r /home/gaubongs/api.thubongstore.online/tako_shopping/frontend/build/. /home/gaubongs/thubongstore.online